import type {
  Athlete,
  Staff,
  TriageEntry,
  DailyMetric,
  Assessment,
  RehabProgram,
  Channel,
  Message,
  Workout,
  AssessmentNode,
  ScheduleEvent,
  AttendanceRecord,
  AuditLog,
  EscalationRecord,
} from "@/types";

// ---- Staff ----
export const mockStaff: Staff[] = [
  {
    id: "staff-1",
    org_id: "org-1",
    team_id: "team-1",
    name: "山田 太郎",
    email: "yamada@pace.fc",
    role: "master",
    is_leader: true,
    is_active: true,
  },
  {
    id: "staff-2",
    org_id: "org-1",
    team_id: "team-1",
    name: "鈴木 花子",
    email: "suzuki@pace.fc",
    role: "AT",
    is_leader: true,
    is_active: true,
  },
  {
    id: "staff-3",
    org_id: "org-1",
    team_id: "team-1",
    name: "田中 次郎",
    email: "tanaka@pace.fc",
    role: "PT",
    is_leader: false,
    is_active: true,
  },
  {
    id: "staff-4",
    org_id: "org-1",
    team_id: "team-1",
    name: "中村 健",
    email: "nakamura@pace.fc",
    role: "S&C",
    is_leader: true,
    is_active: true,
  },
];

// ---- Athletes ----
export const mockAthletes: Athlete[] = [
  {
    id: "athlete-1",
    org_id: "org-1",
    team_id: "team-1",
    name: "田中 健太",
    position: "FW",
    number: 9,
    age: 22,
    sex: "male",
    status: "critical",
    hp: 38,
    nrs: 7,
    hrv: 42.1,
    acwr: 1.62,
    last_updated: "2026-03-21T09:15:00",
  },
  {
    id: "athlete-2",
    org_id: "org-1",
    team_id: "team-1",
    name: "鈴木 大輔",
    position: "MF",
    number: 8,
    age: 24,
    sex: "male",
    status: "watchlist",
    hp: 62,
    nrs: 4,
    hrv: 59.8,
    acwr: 1.38,
    last_updated: "2026-03-21T08:45:00",
  },
  {
    id: "athlete-3",
    org_id: "org-1",
    team_id: "team-1",
    name: "山田 翔",
    position: "DF",
    number: 5,
    age: 26,
    sex: "male",
    status: "watchlist",
    hp: 68,
    nrs: 2,
    hrv: 54.3,
    acwr: 1.12,
    last_updated: "2026-03-21T08:30:00",
  },
  {
    id: "athlete-4",
    org_id: "org-1",
    team_id: "team-1",
    name: "小林 翼",
    position: "MF",
    number: 6,
    age: 21,
    sex: "male",
    status: "normal",
    hp: 82,
    nrs: 0,
    hrv: 71.2,
    acwr: 1.05,
    last_updated: "2026-03-21T08:20:00",
  },
  {
    id: "athlete-5",
    org_id: "org-1",
    team_id: "team-1",
    name: "伊藤 陽介",
    position: "GK",
    number: 1,
    age: 25,
    sex: "male",
    status: "normal",
    hp: 88,
    nrs: 0,
    hrv: 74.5,
    acwr: 0.98,
    last_updated: "2026-03-21T08:10:00",
  },
  {
    id: "athlete-6",
    org_id: "org-1",
    team_id: "team-1",
    name: "渡辺 優",
    position: "DF",
    number: 3,
    age: 23,
    sex: "male",
    status: "normal",
    hp: 79,
    nrs: 1,
    hrv: 68.0,
    acwr: 1.1,
    last_updated: "2026-03-21T08:05:00",
  },
];

// ---- Triage ----
export const mockTriageEntries: TriageEntry[] = [
  {
    athlete_id: "athlete-1",
    athlete_name: "田中 健太",
    position: "FW",
    priority: "critical",
    triggers: ["nrs_spike", "hrv_drop", "acwr_exceeded"],
    nrs: 7,
    hrv: 42.1,
    acwr: 1.62,
    pace_inference_label: "足関節可動域制限パターンA",
    pace_inference_confidence: 82,
    last_updated: "2026-03-21T09:15:00",
  },
  {
    athlete_id: "athlete-2",
    athlete_name: "鈴木 大輔",
    position: "MF",
    priority: "watchlist",
    triggers: ["subjective_objective_discrepancy"],
    nrs: 4,
    hrv: 59.8,
    acwr: 1.38,
    pace_inference_label: "膝関節メカニカルストレスパターン",
    pace_inference_confidence: 63,
    last_updated: "2026-03-21T08:45:00",
  },
  {
    athlete_id: "athlete-3",
    athlete_name: "山田 翔",
    position: "DF",
    priority: "watchlist",
    triggers: ["baseline_deviation"],
    nrs: 2,
    hrv: 54.3,
    acwr: 1.12,
    pace_inference_label: "HRV乖離のみ",
    pace_inference_confidence: 45,
    last_updated: "2026-03-21T08:30:00",
  },
];

// ---- Daily Metrics (14 days) ----
function generateMetrics(athleteId: string, baseNrs: number, baseHrv: number, baseAcwr: number): DailyMetric[] {
  const metrics: DailyMetric[] = [];
  for (let i = 13; i >= 0; i--) {
    const date = new Date("2026-03-21");
    date.setDate(date.getDate() - i);
    metrics.push({
      id: `metric-${athleteId}-${i}`,
      athlete_id: athleteId,
      date: date.toISOString().split("T")[0],
      nrs: Math.max(0, Math.min(10, baseNrs + (Math.random() - 0.5) * 2)),
      hrv: Math.max(20, baseHrv + (Math.random() - 0.5) * 10),
      acwr: Math.max(0.5, Math.min(2.0, baseAcwr + (Math.random() - 0.5) * 0.2)),
      sleep_score: Math.floor(Math.random() * 3) + 3,
      subjective_condition: Math.floor(Math.random() * 2) + 3,
      hp_computed: Math.max(20, Math.min(100, 80 - baseNrs * 5 + (Math.random() - 0.5) * 10)),
    });
  }
  return metrics;
}

export const mockMetrics: Record<string, DailyMetric[]> = {
  "athlete-1": generateMetrics("athlete-1", 6, 44, 1.55),
  "athlete-2": generateMetrics("athlete-2", 3.5, 60, 1.35),
  "athlete-3": generateMetrics("athlete-3", 2, 55, 1.1),
  "athlete-4": generateMetrics("athlete-4", 0.5, 70, 1.05),
};

// ---- Assessment Nodes (F1 Acute sample) ----
export const mockAssessmentNodes: AssessmentNode[] = [
  {
    node_id: "RF_001",
    file_type: "F1_Acute",
    phase: "RedFlag",
    category: "clinical",
    question_text: "頭部への衝撃または意識消失がありましたか？",
    target_axis: "head_neck",
    lr_yes: 8.5,
    lr_no: 0.12,
    kappa: 0.82,
    routing_rules: [],
    prescription_tags: [],
    contraindication_tags: ["all_activity"],
    time_decay_lambda: 0,
    information_gain: 0.85,
  },
  {
    node_id: "RF_002",
    file_type: "F1_Acute",
    phase: "RedFlag",
    category: "clinical",
    question_text: "神経症状（しびれ・麻痺・感覚異常）がありますか？",
    target_axis: "spine_neural",
    lr_yes: 9.2,
    lr_no: 0.08,
    kappa: 0.88,
    routing_rules: [],
    prescription_tags: [],
    contraindication_tags: ["all_activity"],
    time_decay_lambda: 0,
    information_gain: 0.92,
  },
  // ---- 主訴（Chief Complaint） ----
  {
    node_id: "P0_001",
    file_type: "F1_Acute",
    phase: "主訴",
    category: "contextual",
    question_text: "痛みは局所的ですか（一か所に限定）？",
    target_axis: "localization",
    lr_yes: 2.1,
    lr_no: 0.45,
    kappa: 0.75,
    routing_rules: ["P0_002", "P0_003"],
    prescription_tags: [],
    contraindication_tags: [],
    time_decay_lambda: 0.01,
    information_gain: 0.72,
  },
  {
    node_id: "P0_002",
    file_type: "F1_Acute",
    phase: "主訴",
    category: "anatomical",
    question_text: "受傷部位は下肢（股関節から足先）ですか？",
    target_axis: "lower_body",
    lr_yes: 1.8,
    lr_no: 0.3,
    kappa: 0.79,
    routing_rules: ["ANK_001", "KNEE_001"],
    prescription_tags: [],
    contraindication_tags: [],
    time_decay_lambda: 0.01,
    information_gain: 0.68,
  },
  // ---- 視診（Inspection） ----
  {
    node_id: "KNEE_001",
    file_type: "F1_Acute",
    phase: "視診",
    category: "inspection",
    question_text: "膝関節に腫脹（膨れ・むくみ）が視認できますか？",
    target_axis: "knee",
    lr_yes: 5.1,
    lr_no: 0.18,
    kappa: 0.85,
    routing_rules: ["KNEE_002"],
    prescription_tags: ["ice_compression"],
    contraindication_tags: ["knee_impact", "bilateral_jump"],
    time_decay_lambda: 0.03,
    information_gain: 0.91,
  },
  // ---- 動作確認（Functional Movement） ----
  {
    node_id: "ANK_001",
    file_type: "F1_Acute",
    phase: "動作確認",
    category: "functional",
    question_text: "足関節の背屈（つま先を上げる動作）時に痛みがありますか？",
    target_axis: "ankle",
    lr_yes: 4.2,
    lr_no: 0.22,
    kappa: 0.81,
    routing_rules: ["ANK_002"],
    prescription_tags: ["ankle_mobilization"],
    contraindication_tags: ["ankle_impact"],
    time_decay_lambda: 0.02,
    information_gain: 0.89,
  },
  // ---- スペシャルテスト（Special Tests） ----
  {
    node_id: "KNEE_002",
    file_type: "F1_Acute",
    phase: "スペシャルテスト",
    category: "special_test",
    question_text: "McMurrayテスト（膝内側・外側圧迫回旋）で疼痛再現がありますか？",
    target_axis: "meniscus",
    lr_yes: 6.3,
    lr_no: 0.15,
    kappa: 0.88,
    routing_rules: [],
    prescription_tags: ["meniscus_rehab"],
    contraindication_tags: ["knee_rotation", "deep_squat"],
    time_decay_lambda: 0.02,
    information_gain: 0.88,
  },
  {
    node_id: "ANK_002",
    file_type: "F1_Acute",
    phase: "スペシャルテスト",
    category: "special_test",
    question_text: "片脚スクワット時に膝が内側に崩れますか（動的外反）？",
    target_axis: "ankle_kinetic_chain",
    lr_yes: 3.8,
    lr_no: 0.31,
    kappa: 0.77,
    routing_rules: [],
    prescription_tags: ["hip_strengthening"],
    contraindication_tags: ["bilateral_jump"],
    time_decay_lambda: 0.02,
    information_gain: 0.82,
  },
];

// ---- Active Assessment ----
export const mockActiveAssessment: Assessment = {
  id: "assess-1",
  athlete_id: "athlete-1",
  staff_id: "staff-2",
  assessment_type: "F1_Acute",
  status: "in_progress",
  responses: [
    { node_id: "RF_001", answer: "no", timestamp: "2026-03-21T09:00:00" },
    { node_id: "RF_002", answer: "no", timestamp: "2026-03-21T09:01:00" },
    { node_id: "P0_001", answer: "yes", timestamp: "2026-03-21T09:02:00" },
    { node_id: "P0_002", answer: "yes", timestamp: "2026-03-21T09:03:00" },
    { node_id: "ANK_001", answer: "yes", timestamp: "2026-03-21T09:04:00" },
    { node_id: "ANK_002", answer: "yes", timestamp: "2026-03-21T09:05:00" },
    { node_id: "KNEE_001", answer: "no", timestamp: "2026-03-21T09:06:00" },
  ],
  differentials: [
    { diagnosis_code: "ANK_DX_001", label: "足関節可動域制限パターンA", probability: 0.82 },
    { diagnosis_code: "KNEE_DX_002", label: "膝外側ストレスパターン", probability: 0.44 },
    { diagnosis_code: "KNEE_DX_001", label: "膝蓋腱周囲ストレスパターン", probability: 0.31 },
    { diagnosis_code: "MUSC_DX_001", label: "大腿前面筋機能低下パターン", probability: 0.18 },
  ],
  started_at: "2026-03-21T09:00:00",
};

// ---- Rehab Programs ----
export const mockRehabPrograms: RehabProgram[] = [
  {
    id: "rehab-1",
    athlete_id: "athlete-1",
    diagnosis_code: "ANK_DX_001",
    diagnosis_label: "右足関節II度捻挫",
    current_phase: 1,
    start_date: "2026-03-19",
    estimated_rtp_date: "2026-03-28",
    status: "active",
    approval_status: "approved",
    doctor_name: "山田太郎",
    doctor_institution: "東京スポーツ整形外科",
    diagnosis_confirmed_at: "2026-03-19",
    rom: 8,
    swelling_grade: 2,
    lsi_percent: 45,
  },
  {
    id: "rehab-2",
    athlete_id: "athlete-2",
    diagnosis_code: "KNEE_DX_005",
    diagnosis_label: "左膝関節メカニカルストレスパターン",
    current_phase: 3,
    start_date: "2026-02-21",
    estimated_rtp_date: "2026-04-10",
    status: "active",
    approval_status: "pending",
    doctor_name: "鈴木一郎",
    doctor_institution: "大阪スポーツクリニック",
    rom: 118,
    swelling_grade: 0,
    lsi_percent: 76,
  },
];

// ---- Workout (AI Generated) ----
export const mockRehabWorkout: Workout = {
  id: "workout-1",
  athlete_id: "athlete-1",
  type: "individual",
  generated_by_ai: true,
  generated_at: "2026-03-21T08:00:00",
  menu: [
    {
      exercise_id: "ex-001",
      exercise_name: "アイシング",
      sets: 1,
      reps_or_time: "15",
      unit: "min",
      reason: "急性期の腫脹・疼痛管理のため",
    },
    {
      exercise_id: "ex-002",
      exercise_name: "トーグリップ（タオルギャザー）",
      sets: 3,
      reps_or_time: "30",
      unit: "reps",
      rpe: 11,
      cues: "ゆっくりとタオルを掴む動作を繰り返す",
      reason: "足内在筋の賦活化。足関節非荷重でも実施可能",
    },
    {
      exercise_id: "ex-003",
      exercise_name: "股関節外転（サイドライイング）",
      sets: 3,
      reps_or_time: "20",
      unit: "reps",
      rpe: 12,
      cues: "骨盤を固定したまま脚を持ち上げる",
      reason: "近位運動連鎖改善。ANK_002陽性のため股関節外転筋強化が優先",
    },
    {
      exercise_id: "ex-004",
      exercise_name: "上肢有酸素（アームエルゴメーター）",
      sets: 1,
      reps_or_time: "20",
      unit: "min",
      rpe: 13,
      reason: "全身コンディション維持。ACWRが1.62と高いため強度を抑制",
    },
  ],
  total_duration_min: 45,
  notes: "足関節荷重禁止（HARD LOCK: ankle_impact）。松葉杖使用継続。明日ROMを再測定すること。",
};

export const mockTeamWorkout: Workout = {
  id: "workout-team-1",
  team_id: "team-1",
  type: "team",
  generated_by_ai: true,
  generated_at: "2026-03-21T07:00:00",
  menu: [
    // ── Block 1: ウォームアップ・コレクティブ (25 min) ─────────────────
    {
      exercise_id: "ex-w-001",
      exercise_name: "ジョグ＆ダイナミックムーブメント",
      sets: 1,
      reps_or_time: "8",
      unit: "min",
      rpe: 9,
      cues: "股関節をしっかり動かす。リズムよく",
      reason: "中枢神経系の賦活。低強度から段階的に体温を上げる",
      block: "ウォームアップ・コレクティブ",
    },
    {
      exercise_id: "ex-w-002",
      exercise_name: "ヒップヒンジ＋グルートアクティベーション",
      sets: 2,
      reps_or_time: "10",
      unit: "reps",
      rpe: 10,
      cues: "骨盤前傾を保ち股関節を折りたたむ。背骨はニュートラル",
      reason: "コレクティブ：股関節主導パターンの定着。近位安定性確保",
      block: "ウォームアップ・コレクティブ",
    },
    {
      exercise_id: "ex-w-003",
      exercise_name: "バンド・クラムシェル",
      sets: 2,
      reps_or_time: "15",
      unit: "reps",
      rpe: 10,
      cues: "上体を動かさず股関節のみ開く。田中：患側のみ非荷重で実施可",
      reason: "股関節外転筋（中殿筋）の選択的賦活。ANK_002陽性者の近位安定性改善",
      block: "ウォームアップ・コレクティブ",
    },
    {
      exercise_id: "ex-w-004",
      exercise_name: "スパイダーマンランジ＋ソラシックローテーション",
      sets: 2,
      reps_or_time: "6",
      unit: "reps",
      rpe: 10,
      cues: "前足は90-90。胸椎の回旋を意識。ゆっくり",
      reason: "モーターコントロール：胸椎-骨盤の分節運動。試合前のモビリティ確保",
      block: "ウォームアップ・コレクティブ",
    },
    {
      exercise_id: "ex-w-005",
      exercise_name: "ラテラルバンドウォーク",
      sets: 2,
      reps_or_time: "12",
      unit: "reps",
      rpe: 11,
      cues: "膝がつま先と同方向。体幹をブレさせない",
      reason: "コレクティブ：動的外反抑制パターンの習得。チームACWR 1.35のため低強度で実施",
      block: "ウォームアップ・コレクティブ",
    },
    // ── Block 2: ストレングス (40 min) ────────────────────────────────
    {
      exercise_id: "ex-w-006",
      exercise_name: "バーベルスクワット",
      sets: 4,
      reps_or_time: "5",
      unit: "reps",
      rpe: 16,
      cues: "バーは肩甲骨に乗せる。膝はつま先方向。ヒップファーストで降りる",
      reason: "最大筋力維持。試合4日前はACWR管理上5RMまでを上限とする。田中・鈴木除外",
      block: "ストレングス",
    },
    {
      exercise_id: "ex-w-007",
      exercise_name: "ルーマニアンデッドリフト（RDL）",
      sets: 4,
      reps_or_time: "6",
      unit: "reps",
      rpe: 15,
      cues: "バーを体に沿わせる。ハムストリングの張りを感じながら降ろす",
      reason: "ポステリアチェーンの強化。ハムストリング肉離れ予防の観点から全選手必須",
      block: "ストレングス",
    },
    {
      exercise_id: "ex-w-008",
      exercise_name: "ブルガリアンスプリットスクワット",
      sets: 3,
      reps_or_time: "8",
      unit: "reps",
      rpe: 15,
      cues: "後ろ足はボックスに乗せる。前膝をつま先より前に出さない",
      reason: "単脚筋力の左右差是正。鈴木：荷重50%（SOFT LOCK対応）",
      block: "ストレングス",
    },
    {
      exercise_id: "ex-w-009",
      exercise_name: "ノルディックハムストリングカール",
      sets: 3,
      reps_or_time: "5",
      unit: "reps",
      rpe: 16,
      cues: "体を倒す際は体幹を一直線に。急激に落とさずエキセントリックを意識",
      reason: "ハムストリング肉離れ予防に最高エビデンス（RR 0.49）。全選手実施必須",
      block: "ストレングス",
    },
    {
      exercise_id: "ex-w-010",
      exercise_name: "ダンベルインクラインプレス",
      sets: 3,
      reps_or_time: "8",
      unit: "reps",
      rpe: 14,
      cues: "肩甲骨を内転させてベンチに当てる。肘は45度外に",
      reason: "上半身ストレングス維持。下肢ロック選手も実施可能",
      block: "ストレングス",
    },
    {
      exercise_id: "ex-w-011",
      exercise_name: "シーテッドケーブルロウ",
      sets: 3,
      reps_or_time: "10",
      unit: "reps",
      rpe: 14,
      cues: "胸を張り肩甲骨を寄せる。肘を脇に引く",
      reason: "肩甲帯後面の強化。投球・接触競技での肩障害予防",
      block: "ストレングス",
    },
    {
      exercise_id: "ex-w-012",
      exercise_name: "カーフレイズ（シングルレッグ）",
      sets: 3,
      reps_or_time: "15",
      unit: "reps",
      rpe: 13,
      cues: "ゆっくり3秒で下ろす。田中：非荷重側のみ",
      reason: "アキレス腱・腓腹筋の反復性損傷予防。エキセントリック主体で実施",
      block: "ストレングス",
    },
    // ── Block 3: プライオメトリクス (20 min) ──────────────────────────
    {
      exercise_id: "ex-w-013",
      exercise_name: "カウンタームーブメントジャンプ（CMJ）",
      sets: 4,
      reps_or_time: "5",
      unit: "reps",
      rpe: 16,
      cues: "着地は膝・足関節でソフトに受ける。反動を使って最大高さへ",
      reason: "弾性エネルギー活用の神経筋適応。田中：bilateral_jump HARD LOCK 除外",
      block: "プライオメトリクス",
    },
    {
      exercise_id: "ex-w-014",
      exercise_name: "ラテラルバウンド（シングルレッグ着地）",
      sets: 3,
      reps_or_time: "8",
      unit: "reps",
      rpe: 16,
      cues: "着地後3秒静止。膝の内倒れ（valgus）なし",
      reason: "内外側方向のパワー発揮と着地安定性。田中：ankle_impact HARD LOCK 除外",
      block: "プライオメトリクス",
    },
    {
      exercise_id: "ex-w-015",
      exercise_name: "ボックスジャンプ（30cm台）",
      sets: 3,
      reps_or_time: "5",
      unit: "reps",
      rpe: 15,
      cues: "踏み台から降りる際は両足同時着地。膝屈曲90度で吸収",
      reason: "垂直パワー維持。ACWR 1.35のため台高は低め設定。田中除外",
      block: "プライオメトリクス",
    },
    {
      exercise_id: "ex-w-016",
      exercise_name: "メディシンボールスラム（3kg）",
      sets: 3,
      reps_or_time: "8",
      unit: "reps",
      rpe: 15,
      cues: "体幹を使い全身でスラム。下肢障害者も参加可能",
      reason: "上肢・体幹の爆発的収縮。全身パワー系の神経筋刺激",
      block: "プライオメトリクス",
    },
    // ── Block 4: コアスタビリティ (20 min) ───────────────────────────
    {
      exercise_id: "ex-w-017",
      exercise_name: "デッドバグ",
      sets: 3,
      reps_or_time: "10",
      unit: "reps",
      rpe: 12,
      cues: "腰椎を床に押し付けたまま対側腕脚を伸ばす。呼気で腹腔内圧を保つ",
      reason: "体幹深部筋（腹横筋・多裂筋）の共同収縮。全選手実施可能",
      block: "コアスタビリティ",
    },
    {
      exercise_id: "ex-w-018",
      exercise_name: "プランク",
      sets: 3,
      reps_or_time: "60",
      unit: "sec",
      rpe: 12,
      cues: "臀部を上げず・下げず一直線。呼吸を止めない",
      reason: "体幹前面スタビリティ。全選手実施。山田：RPE上限14 → このRPEは適合",
      block: "コアスタビリティ",
    },
    {
      exercise_id: "ex-w-019",
      exercise_name: "サイドプランク（足重ね）",
      sets: 3,
      reps_or_time: "45",
      unit: "sec",
      rpe: 13,
      cues: "腰が落ちないよう体幹外側を意識。両側実施",
      reason: "体幹側面スタビリティ。腸腰筋・外腹斜筋の同時活性",
      block: "コアスタビリティ",
    },
    {
      exercise_id: "ex-w-020",
      exercise_name: "ペルビックブリッジ（シングルレッグ）",
      sets: 3,
      reps_or_time: "12",
      unit: "reps",
      rpe: 12,
      cues: "骨盤水平を保つ。浮かせた脚の臀部は落とさない",
      reason: "殿筋＋腰椎骨盤スタビリティ。単脚で体重支持が困難な選手は両足で実施",
      block: "コアスタビリティ",
    },
    {
      exercise_id: "ex-w-021",
      exercise_name: "パロフプレス（バンド）",
      sets: 3,
      reps_or_time: "12",
      unit: "reps",
      rpe: 12,
      cues: "押し出す際に体幹が回旋しないよう抵抗する。左右各実施",
      reason: "抗回旋スタビリティ。投球・キック動作の体幹制御能力向上",
      block: "コアスタビリティ",
    },
    // ── Block 5: クールダウン (15 min) ───────────────────────────────
    {
      exercise_id: "ex-w-022",
      exercise_name: "ジョグ＋ウォーキングクールダウン",
      sets: 1,
      reps_or_time: "5",
      unit: "min",
      rpe: 7,
      reason: "心拍数を漸進的に低下。乳酸除去を促進",
      block: "クールダウン",
    },
    {
      exercise_id: "ex-w-023",
      exercise_name: "スタティックストレッチ（大腿前後面・股関節・ふくらはぎ）",
      sets: 1,
      reps_or_time: "8",
      unit: "min",
      rpe: 7,
      cues: "各部位30秒×2セット。呼吸を緩めてリラックス",
      reason: "筋硬度の低下と副交感神経優位への移行。翌日の疲労軽減",
      block: "クールダウン",
    },
    {
      exercise_id: "ex-w-024",
      exercise_name: "フォームローリング（臀部・大腿外側・ふくらはぎ）",
      sets: 1,
      reps_or_time: "5",
      unit: "min",
      rpe: 7,
      cues: "圧痛点で10秒静止。呼吸を止めない",
      reason: "筋膜リリースによる局所血流改善。翌日のACWR管理上、疲労蓄積を最小化",
      block: "クールダウン",
    },
  ],
  total_duration_min: 120,
  notes: "田中 健太: ankle_impact / bilateral_jump HARD LOCK（ウォームアップ・上肢種目・コアは全参加可）。鈴木 大輔: スクワット荷重50%に調整（SOFT LOCK）。山田 翔: HRV低下継続のためRPE上限14・プライオは観察参加。現在チームACWR 1.35（注意域）のため総負荷量を通常比90%設定。",
};

// ---- Channels ----
export const mockChannels: Channel[] = [
  { id: "ch-1", team_id: "team-1", name: "medical", member_count: 5 },
  { id: "ch-2", team_id: "team-1", name: "team", member_count: 8 },
  { id: "ch-3", team_id: "team-1", name: "s-and-c", member_count: 3 },
  { id: "ch-4", team_id: "team-1", name: "rehab", member_count: 4 },
];

export const mockMessages: Message[] = [
  {
    id: "msg-1",
    channel_id: "ch-1",
    staff: mockStaff[1],
    content: "田中のROM、昨日比で3度改善。腫脹は2+のまま。明日の荷重テスト実施予定。",
    created_at: "2026-03-21T09:30:00",
    read_by: [
      { staff_id: "staff-1", staff_name: "山田 太郎", read_at: "2026-03-21T09:32:00" },
      { staff_id: "staff-3", staff_name: "田中 次郎", read_at: "2026-03-21T09:35:00" },
    ],
  },
  {
    id: "msg-2",
    channel_id: "ch-1",
    staff: mockStaff[0],
    content: "了解。Hard Lockは今週いっぱい継続。画像所見待ちのため判断は木曜以降。@田中次郎 SOAP更新お願いします。",
    created_at: "2026-03-21T09:45:00",
    read_by: [
      { staff_id: "staff-2", staff_name: "鈴木 花子", read_at: "2026-03-21T09:47:00" },
      { staff_id: "staff-3", staff_name: "田中 次郎", read_at: "2026-03-21T09:50:00" },
    ],
  },
  {
    id: "msg-3",
    channel_id: "ch-1",
    staff: mockStaff[2],
    content: "【SOAPより】田中 健太 — 2026/03/21\nS: 「足首が痛くて体重をかけられない。昨日より少し楽」\nO: ROM背屈5°。腫脹2+。荷重時NRS 7→5に改善\nA: 足関節可動域制限パターンA 継続。Stage1クリア基準（ROM15°）未達\nP: 荷重テスト明日実施。アイシング継続。Hard Lock延長",
    created_at: "2026-03-21T10:00:00",
    linked_soap_id: "soap-1",
    cds_disclaimer: true,
    read_by: [
      { staff_id: "staff-1", staff_name: "山田 太郎", read_at: "2026-03-21T10:02:00" },
      { staff_id: "staff-2", staff_name: "鈴木 花子", read_at: "2026-03-21T10:05:00" },
    ],
  },
  {
    id: "msg-4",
    channel_id: "ch-2",
    staff: mockStaff[3],
    content: "今日のチームトレーニングACWR 1.35（注意域）。プライオの台高を30cmに設定。全体負荷量は通常比90%で実施します。",
    created_at: "2026-03-21T07:30:00",
    read_by: [
      { staff_id: "staff-1", staff_name: "山田 太郎", read_at: "2026-03-21T07:45:00" },
      { staff_id: "staff-2", staff_name: "鈴木 花子", read_at: "2026-03-21T07:50:00" },
    ],
  },
  {
    id: "msg-5",
    channel_id: "ch-3",
    staff: mockStaff[3],
    content: "山田のHRV継続低下中。今週のストレングスはRPE上限14。プライオは観察参加のみ。",
    created_at: "2026-03-21T08:00:00",
    read_by: [
      { staff_id: "staff-1", staff_name: "山田 太郎", read_at: "2026-03-21T08:10:00" },
    ],
  },
  {
    id: "msg-6",
    channel_id: "ch-4",
    staff: mockStaff[2],
    content: "鈴木のLSI 76%確認。Phase 3継続。来週にイソキネティックテスト予定。",
    created_at: "2026-03-21T10:30:00",
    read_by: [],
  },
];

// ---- Schedule Events ----
export const mockScheduleEvents: ScheduleEvent[] = [
  { id: "evt-1", team_id: "team-1", title: "チーム練習", event_type: "practice", date: "2026-03-16", start_time: "16:00", end_time: "18:00", location: "メインフィールド", workout_id: "workout-team-1", created_by_staff_id: "staff-1", notes: "強化期W3。ストレングス+プライオ中心", estimated_rpe: 15, estimated_duration_min: 120 },
  { id: "evt-2", team_id: "team-1", title: "リカバリーセッション", event_type: "recovery", date: "2026-03-17", start_time: "10:00", end_time: "10:45", location: "トレーニングルーム", created_by_staff_id: "staff-2", estimated_rpe: 8, estimated_duration_min: 45 },
  { id: "evt-3", team_id: "team-1", title: "テクニカル練習", event_type: "practice", date: "2026-03-18", start_time: "16:00", end_time: "17:30", location: "メインフィールド", created_by_staff_id: "staff-1", notes: "戦術確認・セットプレー", estimated_rpe: 13, estimated_duration_min: 90 },
  { id: "evt-4", team_id: "team-1", title: "スタッフミーティング", event_type: "meeting", date: "2026-03-19", start_time: "09:00", end_time: "10:00", location: "会議室", created_by_staff_id: "staff-1", notes: "試合前コンディション共有" },
  { id: "evt-5", team_id: "team-1", title: "前日調整練習", event_type: "practice", date: "2026-03-20", start_time: "16:00", end_time: "17:40", location: "メインフィールド", created_by_staff_id: "staff-1", notes: "軽負荷。試合前日のためRPE上限13", estimated_rpe: 11, estimated_duration_min: 100 },
  { id: "evt-6", team_id: "team-1", title: "リーグ戦 第8節", event_type: "match", date: "2026-03-21", start_time: "14:00", end_time: "16:00", location: "市営競技場", opponent: "FC東京B", created_by_staff_id: "staff-1", estimated_rpe: 17, estimated_duration_min: 90 },
  { id: "evt-7", team_id: "team-1", title: "試合翌日リカバリー", event_type: "recovery", date: "2026-03-22", start_time: "10:00", end_time: "10:45", location: "トレーニングルーム", created_by_staff_id: "staff-2", estimated_rpe: 7, estimated_duration_min: 45 },
  { id: "evt-8", team_id: "team-1", title: "チーム練習", event_type: "practice", date: "2026-03-23", start_time: "16:00", end_time: "18:00", location: "メインフィールド", created_by_staff_id: "staff-1", estimated_rpe: 14, estimated_duration_min: 120 },
  { id: "evt-9", team_id: "team-1", title: "強化練習（S&C）", event_type: "practice", date: "2026-03-25", start_time: "15:00", end_time: "17:30", location: "メインフィールド", created_by_staff_id: "staff-4", notes: "ストレングス重点", estimated_rpe: 16, estimated_duration_min: 150 },
  { id: "evt-10", team_id: "team-1", title: "リーグ戦 第9節", event_type: "match", date: "2026-03-28", start_time: "13:00", end_time: "15:00", location: "東京スタジアム（アウェイ）", opponent: "横浜FCユース", created_by_staff_id: "staff-1", estimated_rpe: 17, estimated_duration_min: 90 },
];

// ---- Attendance Records ----
export const mockAttendance: AttendanceRecord[] = [
  { id: "att-1-1", event_id: "evt-1", athlete_id: "athlete-1", athlete_name: "田中 健太", status: "injured_out", notes: "足関節損傷 別メニュー実施" },
  { id: "att-1-2", event_id: "evt-1", athlete_id: "athlete-2", athlete_name: "鈴木 大輔", status: "present", rpe_reported: 14 },
  { id: "att-1-3", event_id: "evt-1", athlete_id: "athlete-3", athlete_name: "山田 翔", status: "present", rpe_reported: 13 },
  { id: "att-1-4", event_id: "evt-1", athlete_id: "athlete-4", athlete_name: "小林 翼", status: "present", rpe_reported: 15 },
  { id: "att-1-5", event_id: "evt-1", athlete_id: "athlete-5", athlete_name: "伊藤 陽介", status: "present", rpe_reported: 14 },
  { id: "att-1-6", event_id: "evt-1", athlete_id: "athlete-6", athlete_name: "渡辺 優", status: "absent", notes: "学業都合" },
  { id: "att-3-1", event_id: "evt-3", athlete_id: "athlete-1", athlete_name: "田中 健太", status: "injured_out" },
  { id: "att-3-2", event_id: "evt-3", athlete_id: "athlete-2", athlete_name: "鈴木 大輔", status: "present", rpe_reported: 13 },
  { id: "att-3-3", event_id: "evt-3", athlete_id: "athlete-3", athlete_name: "山田 翔", status: "present", rpe_reported: 12 },
  { id: "att-3-4", event_id: "evt-3", athlete_id: "athlete-4", athlete_name: "小林 翼", status: "present", rpe_reported: 14 },
  { id: "att-3-5", event_id: "evt-3", athlete_id: "athlete-5", athlete_name: "伊藤 陽介", status: "present", rpe_reported: 13 },
  { id: "att-3-6", event_id: "evt-3", athlete_id: "athlete-6", athlete_name: "渡辺 優", status: "present", rpe_reported: 12 },
  { id: "att-5-1", event_id: "evt-5", athlete_id: "athlete-1", athlete_name: "田中 健太", status: "injured_out" },
  { id: "att-5-2", event_id: "evt-5", athlete_id: "athlete-2", athlete_name: "鈴木 大輔", status: "present", rpe_reported: 11 },
  { id: "att-5-3", event_id: "evt-5", athlete_id: "athlete-3", athlete_name: "山田 翔", status: "present", rpe_reported: 10 },
  { id: "att-5-4", event_id: "evt-5", athlete_id: "athlete-4", athlete_name: "小林 翼", status: "present", rpe_reported: 12 },
  { id: "att-5-5", event_id: "evt-5", athlete_id: "athlete-5", athlete_name: "伊藤 陽介", status: "present", rpe_reported: 11 },
  { id: "att-5-6", event_id: "evt-5", athlete_id: "athlete-6", athlete_name: "渡辺 優", status: "late", rpe_reported: 10, notes: "30分遅刻" },
];

// ---- CDS Audit Logs ----
export const mockAuditLogs: AuditLog[] = [
  {
    id: "audit-1",
    timestamp: "2026-03-21T09:00:00",
    staff_id: "staff-2",
    staff_name: "鈴木 花子",
    staff_role: "AT",
    action_type: "assessment_completed",
    athlete_id: "athlete-1",
    athlete_name: "田中 健太",
    ai_assisted: true,
    disclaimer_shown: true,
    cds_version: "PACE-CDS-v1.2.0",
    session_id: "sess-abc-001",
    notes: "下肢：足関節。鑑別候補3件表示。免責確認済み",
  },
  {
    id: "audit-2",
    timestamp: "2026-03-21T09:15:00",
    staff_id: "staff-2",
    staff_name: "鈴木 花子",
    staff_role: "AT",
    action_type: "soap_saved",
    athlete_id: "athlete-1",
    athlete_name: "田中 健太",
    ai_assisted: true,
    disclaimer_shown: true,
    cds_version: "PACE-CDS-v1.2.0",
    notes: "AI補助入力使用。内容を有資格者が確認・編集のうえ保存",
  },
  {
    id: "audit-3",
    timestamp: "2026-03-21T09:20:00",
    staff_id: "staff-2",
    staff_name: "鈴木 花子",
    staff_role: "AT",
    action_type: "escalation_sent",
    athlete_id: "athlete-1",
    athlete_name: "田中 健太",
    ai_assisted: false,
    disclaimer_shown: true,
    cds_version: "PACE-CDS-v1.2.0",
    notes: "エスカレーション送信先: PT（田中次郎）。レッドフラッグ検出に基づく",
  },
  {
    id: "audit-4",
    timestamp: "2026-03-21T10:00:00",
    staff_id: "staff-1",
    staff_name: "山田 太郎",
    staff_role: "master",
    action_type: "menu_approved",
    athlete_id: "athlete-1",
    athlete_name: "田中 健太",
    ai_assisted: true,
    disclaimer_shown: true,
    cds_version: "PACE-CDS-v1.2.0",
    notes: "AI生成リハビリメニューを内容確認のうえ承認・配信",
  },
  {
    id: "audit-5",
    timestamp: "2026-03-21T10:30:00",
    staff_id: "staff-1",
    staff_name: "山田 太郎",
    staff_role: "master",
    action_type: "lock_issued",
    athlete_id: "athlete-1",
    athlete_name: "田中 健太",
    ai_assisted: false,
    disclaimer_shown: false,
    cds_version: "PACE-CDS-v1.2.0",
    notes: "ankle_impact HARD LOCK 発令。有資格者判断",
  },
  {
    id: "audit-6",
    timestamp: "2026-03-21T11:00:00",
    staff_id: "staff-3",
    staff_name: "田中 次郎",
    staff_role: "PT",
    action_type: "differential_viewed",
    athlete_id: "athlete-2",
    athlete_name: "鈴木 大輔",
    ai_assisted: true,
    disclaimer_shown: true,
    cds_version: "PACE-CDS-v1.2.0",
    notes: "PACE推論閲覧。鑑別候補2件確認",
  },
];

// ---- Escalation Records ----
export const mockEscalations: EscalationRecord[] = [
  {
    id: "esc-1",
    created_at: "2026-03-21T09:20:00",
    from_staff_id: "staff-2",
    from_staff_name: "鈴木 花子",
    from_role: "AT",
    to_roles: ["PT"],
    athlete_id: "athlete-1",
    athlete_name: "田中 健太",
    severity: "urgent",
    message: "【緊急エスカレーション】田中 健太 — アセスメントにてレッドフラッグ（神経症状）検出。即時確認をお願いします。PACE-CDS判断支援補助情報を含みます。最終判断は有資格者が行ってください。",
    audit_log_id: "audit-3",
    acknowledged_at: "2026-03-21T09:35:00",
    acknowledged_by_name: "田中 次郎（PT）",
  },
];
