/**
 * PACE v6.0 — Node 5: プレゼンテーション & 監査ログ
 *
 * パイプライン最終出力の組み立て、推論トレースログの生成、
 * NLG スタイルの判定理由テキスト生成を行う。
 *
 * 処理内容:
 *   1. PipelineOutput の組み立て（全ノード結果の統合）
 *   2. InferenceTraceLog の構築（DB 永続化用）
 *   3. NLG テンプレートベースの判定理由テキスト生成（日本語）
 *   4. 法的免責条項の付与
 *
 * 入力: DecisionOutput（Node 4）+ 全ノード結果
 * 出力: NodeResult<PresentationOutput>
 */

import type {
  AthleteContext,
  DailyInput,
  DataQualityReport,
  DecisionOutput,
  FeatureVector,
  InferenceDecision,
  InferenceOutput,
  InferencePriority,
  InferenceTraceLog,
  NodeExecutor,
  NodeId,
  NodeResult,
  PipelineConfig,
  PipelineOutput,
} from '../types';
import { PIPELINE_VERSION } from '../config';

// ---------------------------------------------------------------------------
// 法的免責条項
// ---------------------------------------------------------------------------

/**
 * 法的免責条項テキスト（日本語）。
 *
 * 本システムの出力は医学的診断ではなく、判定支援ツールとしての
 * 参考情報である旨を明示する。
 */
export const LEGAL_DISCLAIMER =
  '本レポートは PACE コンディショニング判定支援システムによる参考情報であり、医学的診断を構成するものではありません。トレーニングの最終判断は、資格を有するメディカルスタッフまたはコーチングスタッフが行ってください。異常を感じた場合は速やかに医療機関を受診してください。';

/**
 * 法的免責条項テキスト（英語）。
 */
export const LEGAL_DISCLAIMER_EN =
  'This report is generated by the PACE conditioning decision support system and does not constitute a medical diagnosis. Final training decisions should be made by qualified medical or coaching staff. If you experience any abnormalities, please consult a medical professional immediately.';

// ---------------------------------------------------------------------------
// UUID 生成
// ---------------------------------------------------------------------------

/**
 * トレース ID 用の UUID v4 を生成する。
 */
function generateTraceId(): string {
  if (
    typeof crypto !== 'undefined' &&
    typeof crypto.randomUUID === 'function'
  ) {
    return crypto.randomUUID();
  }
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(
    /[xy]/g,
    (c) => {
      const r = (Math.random() * 16) | 0;
      const v = c === 'x' ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    },
  );
}

// ---------------------------------------------------------------------------
// NLG テンプレート
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// FIFA 11+ 介入推奨（Level 1a エビデンス）
// ---------------------------------------------------------------------------

/**
 * FIFA 11+ に基づく介入推奨を生成する。
 *
 * エビデンス（Level 1a — 最高レベル）:
 * - FIFA 11+ Ankle SR/メタアナリシス (2025): 足関節傷害 33% 減
 * - FIFA 11+ Lower Back SR (2025): 腰部傷害 63% 減
 */
export function generateFIFA11Recommendations(
  decision: InferenceDecision,
): string[] {
  switch (decision) {
    case 'GREEN':
      return [
        'ウォーミングアップに FIFA 11+ プログラムの実施を推奨します（傷害予防効果: 足関節33%減, 腰部63%減）。',
      ];
    case 'YELLOW':
      return [
        'FIFA 11+ Level 2（中級）のバランス・固有受容覚トレーニングを重点的に実施してください。',
        '練習強度を下げ、神経筋コントロールの質を重視したメニューに切り替えることを推奨します。',
      ];
    case 'ORANGE':
      return [
        'FIFA 11+ Level 1（基礎）の神経筋トレーニングに限定してください。',
        '高速走行・方向転換を含むメニューの大幅な制限を推奨します。',
      ];
    case 'RED':
      return [
        'トレーニング参加を見送り、医療スタッフの評価を受けてください。',
        '復帰時には FIFA 11+ Level 1 から段階的に負荷を戻すプロトコルを推奨します。',
      ];
  }
}

/** 判定色の日本語ラベル */
const DECISION_LABELS: Record<InferenceDecision, string> = {
  RED: '停止',
  ORANGE: '警戒',
  YELLOW: '注意',
  GREEN: '良好',
};

/** 優先度の日本語ラベル */
const PRIORITY_LABELS: Record<InferencePriority, string> = {
  P1_SAFETY: '安全性（P1）',
  P2_MECHANICAL_RISK: '力学的リスク（P2）',
  P3_DECOUPLING: '慢性的不適応（P3）',
  P4_GAS_EXHAUSTION: 'GAS 疲憊期（P4）',
  P5_NORMAL: '正常適応（P5）',
};

/** 成熟モードの日本語ラベル */
const MATURATION_LABELS: Record<string, string> = {
  safety: '安全モード（データ蓄積不足）',
  learning: '学習モード（ベースライン構築中）',
  full: '完全推論モード',
};

/**
 * NLG テンプレートベースの判定サマリーテキストを生成する。
 *
 * テンプレート構造:
 *   [判定色アイコン] コンディション判定: [判定色ラベル]
 *   判定根拠: [優先度ラベル]
 *   [判定理由テキスト]
 *   ---
 *   データ品質: [品質スコア]% | モード: [成熟モード]
 *   ACWR: [値] | 単調性: [値] | プレパレッドネス: [値]
 *   ---
 *   [免責条項]
 *
 * @param decision - 判定結果
 * @param featureVector - 特徴量ベクトル
 * @param dataQuality - データ品質レポート
 * @returns NLG サマリーテキスト
 */
function generateNLGSummary(
  decision: DecisionOutput,
  featureVector: FeatureVector,
  dataQuality: DataQualityReport,
): string {
  const colorIcon = DECISION_COLOR_ICONS[decision.decision];
  const colorLabel = DECISION_LABELS[decision.decision];
  const priorityLabel = PRIORITY_LABELS[decision.priority];
  const maturationLabel =
    MATURATION_LABELS[dataQuality.maturationMode] ??
    dataQuality.maturationMode;
  const qualityPercent = Math.round(dataQuality.qualityScore * 100);

  const lines: string[] = [
    `${colorIcon} コンディション判定: ${colorLabel}`,
    `判定根拠: ${priorityLabel}`,
    '',
    decision.reason,
    '',
    '---',
    `データ品質: ${qualityPercent}% | モード: ${maturationLabel}`,
    `ACWR: ${featureVector.acwr.toFixed(2)} | 単調性: ${featureVector.monotonyIndex.toFixed(2)} | プレパレッドネス: ${featureVector.preparedness.toFixed(2)}`,
  ];

  // オーバーライドがある場合
  if (decision.overridesApplied.length > 0) {
    const overrideLabels = decision.overridesApplied.map(
      (o) => OVERRIDE_LABELS[o] ?? o,
    );
    lines.push(`適用オーバーライド: ${overrideLabels.join('、')}`);
  }

  lines.push('---');
  lines.push(LEGAL_DISCLAIMER);

  return lines.join('\n');
}

/** 判定色アイコン */
const DECISION_COLOR_ICONS: Record<InferenceDecision, string> = {
  RED: '[RED]',
  ORANGE: '[ORANGE]',
  YELLOW: '[YELLOW]',
  GREEN: '[GREEN]',
};

/** オーバーライドの日本語ラベル */
const OVERRIDE_LABELS: Record<string, string> = {
  game_day: '試合日',
  acclimatization: '順化期間',
  weight_making: '減量期',
  pipeline_fallback: 'パイプラインフォールバック',
};

// ---------------------------------------------------------------------------
// プレゼンテーション出力型
// ---------------------------------------------------------------------------

/** Node 5 の出力データ */
export interface PresentationOutput {
  /** パイプライン最終出力 */
  pipelineOutput: PipelineOutput;
  /** 推論トレースログ（DB 保存用） */
  traceLog: InferenceTraceLog;
  /** NLG サマリーテキスト */
  nlgSummary: string;
}

/** Node 5 の入力データ */
export interface PresentationInput {
  /** 判定結果（Node 4） */
  decision: DecisionOutput;
  /** 推論結果（Node 3） */
  inference: InferenceOutput;
  /** 特徴量ベクトル（Node 2） */
  featureVector: FeatureVector;
  /** データ品質レポート（Node 1） */
  dataQuality: DataQualityReport;
  /** クリーニング済み入力データ */
  cleanedInput: DailyInput;
  /** 各ノードの実行結果サマリー */
  nodeResults: Record<
    NodeId,
    { success: boolean; executionTimeMs: number; warnings: string[] }
  >;
}

// ---------------------------------------------------------------------------
// Node 5 本体
// ---------------------------------------------------------------------------

/**
 * Node 5 実行モジュール: プレゼンテーション & 監査ログ。
 *
 * 以下の処理を行う:
 * 1. PipelineOutput の組み立て
 * 2. InferenceTraceLog の構築
 * 3. NLG テンプレートベースのサマリーテキスト生成
 * 4. 法的免責条項の付与
 */
export const node5Presentation: NodeExecutor<
  PresentationInput,
  PresentationOutput
> = {
  nodeId: 'node5_presentation',

  async execute(
    input: PresentationInput,
    context: AthleteContext,
    config: PipelineConfig,
  ): Promise<NodeResult<PresentationOutput>> {
    const startMs = performance.now();
    const warnings: string[] = [];

    const traceId = generateTraceId();
    const timestamp = new Date().toISOString();

    // ----- Step 1: PipelineOutput の組み立て -----
    const pipelineOutput: PipelineOutput = {
      traceId,
      athleteId: context.athleteId,
      timestamp,
      decision: input.decision,
      featureVector: input.featureVector,
      inference: input.inference,
      dataQuality: input.dataQuality,
      pipelineVersion: PIPELINE_VERSION,
    };

    // ----- Step 2: InferenceTraceLog の構築 -----
    const traceLog: InferenceTraceLog = {
      traceId,
      athleteId: context.athleteId,
      orgId: context.orgId,
      timestampUtc: timestamp,
      pipelineVersion: PIPELINE_VERSION,
      inferenceSnapshot: {
        inputs: input.cleanedInput,
        appliedConstants: {
          thresholds: config.thresholds,
          ewma: config.ewma,
          preparedness: config.preparedness,
        },
        calculatedMetrics: input.featureVector,
        bayesianComputation: input.inference,
        triggeredRule: input.decision.priority,
        decision: input.decision.decision,
        decisionReason: input.decision.reason,
        overridesApplied: input.decision.overridesApplied,
        nodeResults: input.nodeResults,
      },
    };

    // ----- Step 3: NLG サマリー生成 -----
    const nlgSummary = generateNLGSummary(
      input.decision,
      input.featureVector,
      input.dataQuality,
    );

    // ----- 警告: データ品質が低い場合 -----
    if (input.dataQuality.qualityScore < 0.5) {
      warnings.push(
        `データ品質スコアが低い（${Math.round(input.dataQuality.qualityScore * 100)}%）ため、判定の信頼性が低下しています。`,
      );
    }

    return {
      nodeId: 'node5_presentation',
      success: true,
      executionTimeMs: performance.now() - startMs,
      data: {
        pipelineOutput,
        traceLog,
        nlgSummary,
      },
      warnings,
    };
  },
};
